name: CI

on:
    push:
    pull_request:

jobs:
    build-test:
        runs-on: [self-hosted, linux, x64]
        steps:
          - name: Checkout
            uses: actions/checkout@v4
        
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
                go-version-file: 'go.mod'
        
          - name: Download Dependencies
            run: go mod download
    
          - name: Build
            run: go build -o build/bot ./cmd/bot
    
          - name: Test
            run: go test ./... -v
